services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy   
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 5s
      timeout: 10s
      retries: 3

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      app:
        condition: service_healthy
    
  db:
    container_name: db
    image: mysql:5.7
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  db-data: